### PR TITLE
Fix/column ordering

### LINKED ISSUE #124: Broken sorting in tables
Two issues

1. When attribute has an underscore such as `created_at` the direction is not flipped.
2. When filter is used the sorting link looses the direction, like `order=title_` instead of `order=title_desc`

### PR DESCRIPTION
**Pull request by Linuus**
Fixes #124

### CODE REVIEW

File: test/integration/column_ordering_test.rb [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+    find(link_matcher).click
+    link = find(link_matcher)
+    assert_equal "/articles?order=created_at_asc", link[:href]
+  end
+
+  def test_order_links_when_order_empty
+    visit articles_path(order: "")
+    link = find("#table th.column-created_at a")
+    assert_equal "/articles?order=created_at_desc", link[:href]
+  end
```
Comment (Linuus) [inline test/integration/column_ordering_test.rb]: Do we want this last test? I added it while fixing the bug, not sure if we should keep it.

File: lib/godmin/authorization.rb [hunk 2]
```diff
@@ -22,7 +22,7 @@ def authorize(record, query = nil)
     end
 
     def policy(record)
-      policies[record] ||= PolicyFinder.find(record, engine_namespace).new(admin_user, record)
+      policies[record] ||= PolicyFinder.find(record, engine_wrapper.namespace.to_s.underscore).new(admin_user, record)
```
Comment (Linuus) [inline lib/godmin/authorization.rb]: Can we pass the `engine_wrapper.namespace` instead and change the PolicyFinder to handle that? Might break some backward compatibility though...

File: app/views/godmin/resource/_table.html.erb [hunk 3]
```diff
@@ -6,7 +6,7 @@
           <th></th>
         <% end %>
         <% @resource_service.attrs_for_index.each do |attr| %>
-          <th>
+          <th class="column-<%= attr %>">
```
Comment (Linuus) [inline app/views/godmin/resource/_table.html.erb]: Added the class because it was easier to find the right link in the integration test.
Any thoughts on that? Use `qa--` style?

Comment (jensljungblad) [inline app/views/godmin/resource/_table.html.erb]: Meh, I say leave it

File: lib/godmin/authorization.rb (hunk 2 above)
Comment (jensljungblad) [inline lib/godmin/authorization.rb]: I say pass `engine_wrapper.namespace` instead

File: test/integration/column_ordering_test.rb (hunk 1 above)
Comment (jensljungblad) [inline test/integration/column_ordering_test.rb]: What's the difference between the last one and the first one?

Comment (Linuus) [inline test/integration/column_ordering_test.rb]: The first one has no param[:order] at all. This has an empty param[:order]. It was causing a bug here: https://github.com/varvet/godmin/blob/fix/column-ordering/lib/godmin/helpers/tables.rb#L7

We just did `if params[:order]`. I just used the test while fixing the bug

Comment (jensljungblad) [inline test/integration/column_ordering_test.rb]: Aha. Well then the test should stay I guess!
